# fly.toml app configuration file generated for elev8-server on 2024-12-31T14:26:15+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elev8-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
